name: kp_manajemen_bengkel
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  cloud_firestore: ^4.15.9
  firebase_auth: ^4.17.9
  firebase_core: ^2.27.1
  firebase_database: ^10.4.10
  lottie: ^3.1.2
  flutter:
    sdk: flutter

  #Navbar
  # persistent_bottom_nav_bar: ^4.0.2
  # stylish_bottom_bar: ^1.1.0
  google_nav_bar: ^5.0.6
  flutter_speed_dial: ^7.0.0
  image_picker: ^1.1.1
  firebase_storage: ^11.7.6
  path: ^1.9.0
  intl: ^0.18.1 #Ganti intl dari versi 0.19.0
  flutter_date_pickers: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/icons/
