name: kp_manajemen_bengkel
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  cloud_firestore: ^4.15.9
  firebase_auth: ^4.17.9
  firebase_core: ^2.27.1
  firebase_database: ^10.4.10
  lottie: ^1.3.0
  flutter:
    sdk: flutter

  #Navbar
  # persistent_bottom_nav_bar: ^4.0.2
  # stylish_bottom_bar: ^1.1.0
  google_nav_bar: ^5.0.6
  flutter_speed_dial: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/icons/
